In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

country   age   salary purchased
0  france  21.0  10000.0        no
1   india  11.0  12000.0        no
2   nepal   NaN  13000.0        no
3   india  23.0      NaN       yes
4   india  24.0  14000.0       yes

In [4]:
df.isnull().sum()

country      0
age          2
salary       3
purchased    3
dtype: int64

In [5]:
df = df.dropna(subset=['purchased'])


In [6]:
df.fillna(value=df.mean())

C:\Users\user\AppData\Local\Temp\ipykernel_7876\1364442528.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(value=df.mean())


country        age   salary purchased
0      france  21.000000  10000.0        no
1       india  11.000000  12000.0        no
2       nepal  27.416667  13000.0        no
3       india  23.000000  19500.0       yes
4       india  24.000000  14000.0       yes
6     finland  26.000000  17000.0       yes
7     finland  27.000000  19500.0        no
8       nepal  28.000000  18000.0        no
9   portugual  31.000000  13000.0        no
10  arjentina  30.000000  31000.0       yes
11     france  69.000000  12000.0       yes
13   maldives  18.000000  14500.0        no
14     france  21.000000  60000.0        no

In [7]:
# from sklearn.preprocessing import LabelEncoder
# columns_to_encode = ['country','purchased']  # Add column names as per your data
# encoder = LabelEncoder()

# for column in columns_to_encode:
#     df[column] = encoder.fit_transform(df[column])



In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [9]:
x=encoder.fit_transform(df.country.values.reshape(-1,1)).toarray()

In [10]:
x

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [11]:
df

country   age   salary purchased
0      france  21.0  10000.0        no
1       india  11.0  12000.0        no
2       nepal   NaN  13000.0        no
3       india  23.0      NaN       yes
4       india  24.0  14000.0       yes
6     finland  26.0  17000.0       yes
7     finland  27.0      NaN        no
8       nepal  28.0  18000.0        no
9   portugual  31.0  13000.0        no
10  arjentina  30.0  31000.0       yes
11     france  69.0  12000.0       yes
13   maldives  18.0  14500.0        no
14     france  21.0  60000.0        no

In [12]:
from sklearn.preprocessing import LabelEncoder
l_encoder=LabelEncoder()

In [13]:
y=l_encoder.fit_transform(df.purchased)

In [14]:
y

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [16]:
X_train

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.]])

In [17]:
X_test


array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [19]:
y_train


array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1])

In [20]:
y_test

array([1, 0, 0])

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
sc_x=StandardScaler()

In [24]:
x_train=sc_x.fit_transform(X_train)

In [26]:
x_test=sc_x.transform(X_test)

In [27]:
x_train

array([[-0.33333333,  2.        , -0.65465367, -0.5       ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       , -0.65465367, -0.5       ,  0.        ,
        -0.33333333,  3.        ],
       [-0.33333333, -0.5       , -0.65465367, -0.5       ,  0.        ,
         3.        , -0.33333333],
       [-0.33333333, -0.5       ,  1.52752523, -0.5       ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333,  2.        , -0.65465367, -0.5       ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       ,  1.52752523, -0.5       ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       , -0.65465367,  2.        ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       ,  1.52752523, -0.5       ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       , -0.65465367,  2.        ,  0.        ,
        -0.33333333, -0.33333333],
       [ 3.        , -0.5   

In [28]:
x_test

array([[-0.33333333, -0.5       , -0.65465367,  2.        ,  0.        ,
        -0.33333333, -0.33333333],
       [-0.33333333, -0.5       , -0.65465367, -0.5       ,  0.        ,
         3.        , -0.33333333],
       [-0.33333333, -0.5       , -0.65465367, -0.5       ,  1.        ,
        -0.33333333, -0.33333333]])